import 'package:flutter/material.dart';

const colorSchemeLight = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff006874),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xff99f0ff),
  onPrimaryContainer: Color(0xff001f24),
  secondary: Color(0xff4a6267),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffcde7ec),
  onSecondaryContainer: Color(0xff051f23),
  tertiary: Color(0xff535e7d),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffdae2ff),
  onTertiaryContainer: Color(0xff0e1a37),
  error: Color(0xffba1a1a),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffffdad6),
  onErrorContainer: Color(0xff410002),
  background: Color(0xfffbfcfd),
  onBackground: Color(0xff191c1d),
  surface: Color(0xfffbfcfd),
  onSurface: Color(0xff191c1d),
  surfaceVariant: Color(0xffdbe4e6),
  onSurfaceVariant: Color(0xff3f484a),
  outline: Color(0xff6f797b),
  outlineVariant: Color(0xffbfc8ca),
  inverseSurface: Color(0xff2e3132),
  onInverseSurface: Color(0xffeff1f1),
  inversePrimary: Color(0xff4fd8ec),
  surfaceTint: Color(0xff006874),
);
